### ISSUE TITLE
servo-latest is not updated on download.servo.org

### ISSUE THREAD

**Issue by cbrewster** [servo/download.servo.org#10]
https://download.servo.org/nightly/mac/servo-latest.dmg gives me an old nightly while http://servo-builds.s3-website-us-west-2.amazonaws.com/nightly/mac/servo-latest.dmg is giving me the newest nightly.

cc @edunham

**Comment by edunham** [comment]
Thanks for catching this! The downloads site currently uses CloudFront to provide and require HTTPS, and the issue you saw was CloudFront serving the cached version of the dmg for too long. 

I've dropped the CloudFront distribution's default TTL down to half an hour, so the download.servo.org URL shoudl now be unable to give you an object more than 30 minutes out of date.
