### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by michallepicki** [servo/download.servo.org#12]
![servo](https://cloud.githubusercontent.com/assets/4972756/18969427/6b6501f0-868d-11e6-99fd-0a3e10b6a70d.png)

**Comment by SteVwonder** [comment]
Looks as though this has popped back up again
<img width="486" alt="screen shot 2016-12-29 at 2 49 11 pm" src="https://cloud.githubusercontent.com/assets/874707/21553409/1f6dfeb0-cdd6-11e6-97db-cd143d8269b6.png">

**Comment by larsbergstrom** [comment]
@edunham @metajack @manishearth How do we fix this? The credentials for Let's Encrypt are not in the "servo build secrets" file. Or is there something I can press in cloudfront, etc. to fix this?

**Comment by metajack** [comment]
I believe @edunham set this up. Let's Encrypt doesn't have credentials that I can recall. It uses verification based on special files in the webroot to set up a private key and then uses that when renewing I think. I have no idea how this works on cloudfront, but on my machines I have a cronjob that renews when it is time unattended.

**Comment by aneeshusa** [comment]
I believe @edunham had [started the process](https://github.com/servo/saltfs/issues/423#issuecomment-251173962) for using Amazon Certificate Manager (ACM) which autorenews and has CloudFront integration (IMO easiest option for `download.servo.org`). You might be able to look at status in the dashboard, or it may have been via a support request, I'm not sure.

**Comment by aneeshusa** [comment]
We're now using ACM, thanks to @metajack per https://github.com/servo/saltfs/issues/423#issuecomment-270552925, and this can be closed.
