### ISSUE TITLE
Linux instructions — runservo.sh no longer needed (or present)

### ISSUE THREAD

**Issue by aplaice** [servo/download.servo.org#17]
I think that the Linux usage instructions at: https://download.servo.org/ are slightly outdated  — the tarball (for the Linux Build (64-bit)) no longer contains a `runservo.sh` script, just a `servo` executable. This is obviously very minor.

**Comment by atouchet** [comment]
This was fixed in #13.

**Comment by aneeshusa** [comment]
Thanks, #13 has been merged so this is fixed.
