### ISSUE TITLE
Windows link is broken

### ISSUE THREAD

**Issue by cadeyrn** [servo/download.servo.org#22]
Hi,

there is a download link for Windows Nightly on download.servo.org since https://github.com/servo/download.servo.org/pull/20 but the link is broken (NoSuchKey error). The links for macOS and Linux still working as expected.

**Comment by ghost** [comment]
Duplicate of #21

**Comment by atouchet** [comment]
This was fixed in #21.

**Comment by aneeshusa** [comment]
Closing as fixed by #21 (although Windows happens to be temporarily disabled again right now).
