### ISSUE TITLE
Deploying changes doesn't invalidate cloudfront

### ISSUE THREAD

**Issue by jdm** [servo/download.servo.org#52]
Merging #49 and #51 did not cause download.servo.org to update. I had to to go cloudfront and invalidate index.html manually to make the new content visible.

**Comment by camelid** [comment]
Is this an issue still?

If so, perhaps there's a way to disable caching for certain paths so that manually updates aren't required.

**Comment by jdm** [comment]
This does not appear to be an issue any more.

**Comment by camelid** [comment]
Great :)
