### ISSUE TITLE
Add some tests so we can run bors on this repo

### ISSUE THREAD

**Issue by edunham** [servo/download.servo.org#6]
Incomplete list of ideas of what we should test:
- Code style lint? 
- HTML correctness? 
- Resolvability of any new URLs added
- SRI checksums match static files

**Comment by aneeshusa** [comment]
I think we could use https://github.com/mozilla/html5-lint for HTML validity checking. All the single quotes we have right now are jarring to my eyes.

**Comment by larsbergstrom** [comment]
Landed https://github.com/servo/saltfs/pull/574 and enabled travis - just need the .travis.yml now.

**Comment by aneeshusa** [comment]
I've created #16 for this.

**Comment by aneeshusa** [comment]
We have some tests now and Homu set up.
