### ISSUE TITLE
Link to commit hash tries to download it rather than displaying in browser

### ISSUE THREAD

**Issue by camelid** [servo/download.servo.org#64]
I think S3 treats all unknown file extensions (like `.sha256`) as MIME type `binary/octet-stream`.

**Comment by camelid** [comment]
@jdm could you take a look at this? Thanks!

**Comment by jdm** [comment]
Fixed. I followed https://stackoverflow.com/questions/19100858/how-do-you-change-the-mime-on-amazon-s3.
