### ISSUE TITLE
Infra: servo-latest.tar.gz.sha256 is cached for too long by CloudFront causing sha256 mismatch

### ISSUE THREAD

**Issue by mrl5** [servo/download.servo.org#78]
**TL;DR**: https://download.servo.org/nightly/linux/servo-latest.tar.gz.sha256 in Firefox gives invalid sha256sum of https://download.servo.org/nightly/linux/servo-latest.tar.gz - however in curl I see valid sha256sum. 

```bash
date -uIseconds &&
  wget -q https://download.servo.org/nightly/linux/servo-latest.tar.gz &&
  wget -q https://download.servo.org/nightly/linux/servo-latest.tar.gz.sha256 &&
  sha256sum servo-latest.tar.gz; \
  cat servo-latest.tar.gz.sha256
```
as expected this produces
```
2021-12-31T15:14:28+00:00
8dcdd5b8b52dfd11dcdb1f4787ca4c037505ba95d79662d1474a61c167252edb  servo-latest.tar.gz
8dcdd5b8b52dfd11dcdb1f4787ca4c037505ba95d79662d1474a61c167252edb
```

however when I visit https://download.servo.org/nightly/linux/servo-latest.tar.gz.sha256 in my Firefox I get:
```
81739c1c16f5846b2986af52a9513574de12877a7849398e54bcabb5e68e7832
```

this can be reproduced in `curl`:
```bash
curl -i \
  'https://download.servo.org/nightly/linux/servo-latest.tar.gz.sha256' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' \
  -H 'Accept-Language: en-US,en;q=0.5' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'DNT: 1' \
  -H 'Connection: keep-alive' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache'
```
produces
```
HTTP/2 200 
content-type: text/plain
content-length: 64
date: Thu, 30 Dec 2021 21:13:51 GMT
last-modified: Thu, 30 Dec 2021 06:08:16 GMT
etag: "4d92fb5d7d5a41477eceb728cea58de0"
accept-ranges: bytes
server: AmazonS3
x-cache: Hit from cloudfront
via: 1.1 89b8117bd9270d922b4549a30cd5ce50.cloudfront.net (CloudFront)
x-amz-cf-pop: WAW50-C1
x-amz-cf-id: 5BHbzy1yLJLyBBBsxgOViQvi7oI5WVlUFxYjcizGrncpBSNsxcYq9w==
age: 65012

81739c1c16f5846b2986af52a9513574de12877a7849398e54bcabb5e68e7832
```

for comparison
```bash
curl -i \
  'https://download.servo.org/nightly/linux/servo-latest.tar.gz.sha256' 
```
produces
```
HTTP/2 200 
content-type: text/plain
content-length: 64
date: Fri, 31 Dec 2021 14:59:55 GMT
last-modified: Fri, 31 Dec 2021 05:59:32 GMT
etag: "68088e1497cedb287e210daed4fa1fb9"
accept-ranges: bytes
server: AmazonS3
x-cache: Hit from cloudfront
via: 1.1 8bc9c1665a1b070ea4ccaae56c1f88b7.cloudfront.net (CloudFront)
x-amz-cf-pop: WAW50-C1
x-amz-cf-id: 4e0jzoPsapp0fBtrwb7QDZr2_cM0x8aBdsL6M-V0xr75mVk4JnnuFA==
age: 1268

8dcdd5b8b52dfd11dcdb1f4787ca4c037505ba95d79662d1474a61c167252edb
```

**Comment by mrl5** [comment]
@jdm I'm not sure if [servo/download.servo.org](https://github.com/servo/download.servo.org) repo is a correct place for this bug.

I believe I'm right because the bug is about cloufront configuration and/or the way nightly build artifacts are uploaded to S3 when this repo hosts the html+css of `download.servo.org`

I think the fix that invalidates the CloudFront cache on each artifact upload should be done here: https://github.com/servo/servo/blob/master/python/servo/package_commands.py (example how to do it from boto: https://gist.github.com/jolexa/e58ea2ec19cf3067d0ddfbdc98bbaf6d)

If you would like to additionally cache the `sha256` once as described https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cache-hit-ratio.html#cache-hit-ratio-remove-accept-encoding then you would need to find a place where CloudFront stack is defined - tbh I searched whole https://github.com/servo/ namespace and couldnt find it

**Comment by jdm** [comment]
Thanks for the pointer about where the cache invalidation can occur. I'm going to leave the issue here because it's where the user actually experiences the issue, so it makes more sense to track it here.

**Comment by mrl5** [comment]
um, I can do the PR to [servo/servo](https://github.com/servo/servo) that would create cache invalidation in [package_commands.py](https://github.com/servo/servo/blob/master/python/servo/package_commands.py) but I'd like to be sure about two things before I do it:
- that I have green light from maintainer(s) (so that I don't waste time for changes that will be declined because this approach is not the desired one)
- I would need to ensure what's the S3 bucket structure so that I know that `nightly/servo-latest.*` glob can be used for invalidation

when it comes to AWS costs:
> You can submit a certain number of invalidation paths each month for free. If you submit more than the allotted number of invalidation paths in a month, you pay a fee for each invalidation path that you submit.

> The first 1,000 invalidation paths that you submit per month are free; you pay for each invalidation path over 1,000 in a month. An invalidation path can be for a single file (such as /images/logo.jpg) or for multiple files (such as /images/*). A path that includes the * wildcard counts as one path even if it causes CloudFront to invalidate thousands of files.
> 
> The maximum of 1,000 free invalidation paths per month applies to the total number of invalidation paths across all of the distributions that you create with one AWS account. 

(from: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html)

===
when it comes to https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cache-hit-ratio.html#cache-hit-ratio-remove-accept-encoding

I only found https://github.com/servo/servo/wiki/Infrastructure and looks like this wiki page is outdated or your CloudFront configuration is manual - so I guess I can't do anything more than linking this advice from AWS docs

**Comment by jdm** [comment]
I don't think `nightly/servo-latest.*` will work, since we have:
* `nightly/uwp/servo-latest.zip.sha256`
* `nightly/windows-msvc/servo-latest.exe.sha256`
* `nightly/windows-msvc/servo-latest.zip.sha256`
* `nightly/mac/servo-latest.dmg.sha256`
* `nightly/linux/servo-latest.tar.gz.sha256`

And yes, the cloudfront configuration is manual.

**Comment by jdm** [comment]
The s3 bucket structure can be inspected with https://servo-builds2.s3.amazonaws.com/?prefix=nightly/mac/

**Comment by mrego** [comment]
Let's track this at https://github.com/servo/servo/issues/29034, as download.servo.org has been integrated into the website servo.org/download
