### ISSUE TITLE
Automate uploads to S3

### ISSUE THREAD

**Issue by aneeshusa** [servo/download.servo.org#8]
I'm guessing this will want to use the upload_nightly.sh script from Servo and run on Buildbot, similar to the existing `doc` builder.

**Comment by edunham** [comment]
We can do the same thing as https://github.com/rust-lang/rust-www/blob/master/.travis.yml, with AWS creds good only for touching the HTML and CSS files in Travis's encrypted environment variables, to automatically upload whenever code's merged to this repo. 

The threat model against this is that if someone compromised Travis's secret storage, they could edit the index to temporarily link users to malicious downloads hosted on another domain. I think this is an acceptable risk to take for the convenience of having an index page that's always up to date with no additional effort beyond merging PRs.

@larsbergstrom, @metajack, thoughts?

**Comment by larsbergstrom** [comment]
Yes, this is fantastic! And WAY better than "one of us with s3 perms does a git pull & s3 put"

**Comment by aneeshusa** [comment]
It looks like #28 fixed this?
